# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-XrNx70bFV4ttJkb-y2boBNe0otWscf
"""

print('hello world!')

